### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ToxaEagle123** [armagidon-exception/PosePlugin#36]
Hello! I have installed your plugin. Create a folder with plugin configuration. Gave the players the necessary rights, but after trying to use the commands, he writes that such commands do not exist.

Console log:

[13:07:30 INFO]: Preparing spawn area: 0%
[13:07:30 INFO]: Preparing spawn area: 0%
[13:07:30 INFO]: Preparing spawn area: 0%
[13:07:30 INFO]: Preparing spawn area: 1%
[13:07:30 INFO]: Time elapsed: 1752 ms
[13:07:30 INFO]: Preparing start region for dimension minecraft:the_nether
[13:07:31 INFO]: Loaded 0 spawn chunks for world world_nether
[13:07:31 INFO]: Preparing spawn area: 0%
[13:07:31 INFO]: Preparing spawn area: 4%
[13:07:31 INFO]: Time elapsed: 947 ms
[13:07:31 INFO]: Preparing start region for dimension minecraft:the_end
[13:07:32 INFO]: Loaded 0 spawn chunks for world world_the_end
[13:07:32 INFO]: Preparing spawn area: 0%
[13:07:32 INFO]: Preparing spawn area: 5%
[13:07:32 INFO]: Time elapsed: 722 ms
[13:07:32 INFO]: [HideTagAPI] Enabling HideTagAPI v1.0*
[13:07:32 INFO]: [OpenInv] Enabling OpenInv v4.1.5
[13:07:32 INFO]: [PosePlugin] Enabling PosePlugin v2.0.1-beta-2-experimental
[13:07:32 ERROR]: [PosePlugin] Plugin PosePlugin v2.0.1-beta-2-experimental has failed to register events for class ru.armagidon.poseplugin.plugin.listeners.PluginEventListener because ru/armagidon/poseplugin/api/events/StopPosingEvent does not exist.
[13:07:32 ERROR]: [PosePlugin] Plugin PosePlugin v2.0.1-beta-2-experimental has failed to register events for class ru.armagidon.poseplugin.plugin.listeners.MessagePrintingHandler because ru/armagidon/poseplugin/api/events/PostPoseChangeEvent does not exist.
[13:07:32 ERROR]: Error occurred while enabling PosePlugin v2.0.1-beta-2-experimental (Is it up to date?)
java.lang.NoClassDefFoundError: ru/armagidon/poseplugin/api/PosePluginAPI
at ru.armagidon.poseplugin.plugin.command.PluginCommands.initCommands(PluginCommands.java:51) ~[?:?]
at ru.armagidon.poseplugin.PosePlugin.onEnable(PosePlugin.java:41) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-291]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: ru.armagidon.poseplugin.api.PosePluginAPI
at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Paper-291]
at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
... 12 more
[13:07:32 INFO]: [PosePlugin] Disabling PosePlugin v2.0.1-beta-2-experimental
[13:07:32 ERROR]: Error occurred while disabling PosePlugin v2.0.1-beta-2-experimental (Is it up to date?)
java.lang.NoClassDefFoundError: ru/armagidon/poseplugin/api/PosePluginAPI
at ru.armagidon.poseplugin.PosePlugin.onDisable(PosePlugin.java:48) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-291]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: ru.armagidon.poseplugin.api.PosePluginAPI
at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Paper-291]
at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-291](B
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-291]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-291]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: ru.armagidon.poseplugin.api.PosePluginAPI
at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.4.jar:git-Paper-291]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Paper-291]
at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
... 13 more

**Comment by armagidon-exception** [comment]
Put both api and plugin in your plugins folder. Files are named as: PosePluginAPI-version, poseplugin-version
